version: "3"
services:
  geoip_service:
    image: python:3.11-slim-buster
    restart: always
    command: >
        bash -c 'apt-get update -y &&
        apt-get install -y --no-install-recommends curl gcc g++ gnupg unixodbc-dev &&
        pip install --no-cache-dir -r /code/requirements.txt &&
        cd /code &&
        uvicorn app.main:app --port 8080 --host 0.0.0.0  --ssl-keyfile /code/stack/ssl/localhost.key --ssl-certfile /code/stack/ssl/localhost.crt'
    ports:
      - "8001:8080"
    volumes:
      - ./requirements.txt:/code/requirements.txt
      - ./app:/code/app
      - ./stack:/code/stack
    environment:
      IP_INFO_TOKEN: ${IP_INFO_TOKEN}
      TZ: ${TZ}
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  default:
    driver: bridge
